version: '2'

services:
  janus-gateway:
    image: registry:5000/nbycomp/services/ebv/janus:1.0.0
    build:
      context: .
    volumes:
      - ./conf:/opt/janus/etc/janus/
    ports:
      - "8888:8888"
      - "80:80"
      - "7088:7088"
      - "8088:8088"
      - "8188:8188"
      - "8089:8089"
      - "10000-10200:10000-10200/udp"
    environment:
      - DOCKER_IP=${DOCKER_IP}
      - FEED1_LABEL=${FEED1_LABEL}
      - FEED2_LABEL=${FEED2_LABEL}
      - FEED2_USER=${FEED2_USER}
      - FEED2_PASSWORD=${FEED2_PASSWORD}
      - FEED2_URL=${FEED2_URL}
      
